#!/usr/bin/env php
<?php

$target_directory = dirname(__FILE__).'/../CurvatureData/kml';
date_default_timezone_set('UTC');
$tz = new DateTimeZone('UTC');

if (!file_exists(dirname(__FILE__)."/vendor/autoload.php")) {
  $message = "
Error: You must install dependencies by running `composer install` in this directory
before this program can run successfully.

If you do not have composer installed on your machine, you can get it as described
here: https://getcomposer.org/

1. Download the composer.phar to the current directory with:
       curl -sS https://getcomposer.org/installer | php
2. Install dependencies of this package:
       php composer.phar install

";
  die($message);
}
require_once dirname(__FILE__)."/vendor/autoload.php";
require_once dirname(__FILE__)."/lib/Indexer.php";

$loader = new Twig_Loader_Filesystem(dirname(__FILE__).'/templates');
$twig = new Twig_Environment($loader, array(
    // 'cache' => dirname(__FILE__).'/compilation_cache',
));
$twig->addExtension(new Twig_Extensions_Extension_Number);

$indexer = new Indexer($twig, $tz);
$indexer->create_indices($target_directory);

// Add resources
if (!is_dir($target_directory.'/resources')) {
  mkdir($target_directory.'/resources');
}
shell_exec('rsync -av --delete '.escapeshellarg(dirname(__FILE__).'/resources').' '.escapeshellarg($target_directory));
